### ISSUE TITLE
API client lacks a messages attribute

### ISSUE THREAD

**Issue by jm-contreras** [anthropics/anthropic-sdk-python#352]
👋  I'm trying to use the Claude API and I can't even get the client to work properly following [the SDK example](https://docs.anthropic.com/claude/reference/client-sdks#python) to the character. Anything I'm doing wrong?

<img width="646" alt="image" src="https://github.com/anthropics/anthropic-sdk-python/assets/55989773/2d2da778-7c4e-4328-86db-e57da305a619">

**Comment by rattrayalex** [comment]
It looks like you're on an old version of the client library. Try `pip install anthropic --upgrade`

**Comment by march038** [comment]
This doesn't help and I have the same issue installing anthropic to conda through conda or pip.

---> 22 message = anthropic.Anthropic().messages.create(
     23     model="claude-3-opus-20240229",
     24     max_tokens=1024,
     25     temperature= 0.5,
     26     system=system_prompt,
     27     messages=[messages])
     29 print(message.content)

AttributeError: 'Anthropic' object has no attribute 'messages'

**Comment by rattrayalex** [comment]
What is the version of the client you're using?

**Comment by march038** [comment]
> What is the version of the client you're using?

print(anthropic.__version__) 

leads to 0.21.3

**Comment by fanpeeps** [comment]
Same problem with 0.21.3

**Comment by fanpeeps** [comment]
The new way to establish client is with the following (this departs form prior instructions and instructions Claude will provide):

```
from anthropic import Anthropic

claude = Anthropic(api_key=your_api_key)
```

[Prior instructions advised to "import anthropic" and establish client with "client = anthropic.Client(api_key=your_api_key)]

**Comment by rattrayalex** [comment]
Strange… can you share more details about your runtime environment, and a screenshot of it not working with 0.21.3? (similar to the one in the issue description)

**Comment by mikiane** [comment]
Same issue here... Any update?

**Comment by RobertCraigie** [comment]
I would be very surprised if you're actually using the latest version, it's much more likely that your env setup is broken somehow and you're using an old version.

**Comment by mikiane** [comment]
My mistake... Env problem. You were right.

**Comment by rattrayalex** [comment]
Great to hear, thank you @mikiane ! Could you share your fix, for others who might run into this in the future?

**Comment by PeterP22** [comment]
> It looks like you're on an old version of the client library. Try `pip install anthropic --upgrade`

This fixed it for me. Specifically the response = client.beta.tools.messages.create(
    model=MODEL_NAME,
    max_tokens=4096,
    tools=tools,
    messages=[{"role": "user", "content": query}]
)

**Comment by 8enSmith** [comment]
Turned out I was getting this issue as I was using an old version of Anthropic.

Explicitly setting my version of anthropic to latest in my requirements.txt fixed the issue for me. At the time of writing I used `anthropic==0.31.1`

**Comment by mindaika** [comment]
Yeowch: this one got me too. Spend a full day trying to unset httpx Proxies. Turned out I had the anthropic version set to 0.9.0 (it's currently on 0.42.0).

If you have this error: check your anthropic version
