### ISSUE TITLE
Skill use in v0.71.0 doesn't work

### ISSUE THREAD

**Issue by aivisbr** [anthropics/anthropic-sdk-python#1048]
According to [the API documentation](https://docs.claude.com/en/api/skills-guide#using-skills-in-messages), following code example I could use to run Agent Skills:

```
import anthropic

client = anthropic.Anthropic()

response = client.messages.create(
    model="claude-sonnet-4-5-20250929",
    max_tokens=4096,
    betas=["code-execution-2025-08-25", "skills-2025-10-02"],
    container={
        "skills": [
            {
                "type": "anthropic",
                "skill_id": "pptx",
                "version": "latest"
            }
        ]
    },
    messages=[{
        "role": "user",
        "content": "Create a presentation about renewable energy"
    }],
    tools=[{
        "type": "code_execution_20250825",
        "name": "code_execution"
    }]
)
```
But this code doesn't work in version 0.71.0, because I got a TypeError: "TypeError: Messages.create() got an unexpected keyword argument 'container'". It looks like this version still doesn't fully support Agent Skills. Am I right?

**Comment by karpetrosyan** [comment]
I believe it was released as beta, so it should be called like this

```diff
+ response = client.beta.messages.create(
- response = client.messages.create(
```

**Comment by aivisbr** [comment]
Thanks @karpetrosyan - `client.beta.messages.create` worked for me.

**Comment by karpetrosyan** [comment]
Let's not close this until it gets fixed
